# @format

services:
  db:
    image: mysql:8.0
    container_name: estapar-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build: .
    container_name: estapar-backend
    restart: always
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_FLYWAY_ENABLED: true
      GARAGE_SIMULATOR_BASE_URL: http://localhost:3000
      APP_WEBHOOK_URL: http://localhost:3003/webhook
      SERVER_PORT: 3003
    depends_on:
      db:
        condition: service_healthy

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-simulator
    network_mode: "host"
    environment:
      EXTERNAL_API_URL: http://localhost:3003/webhook
    depends_on:
      app:
        condition: service_started

volumes:
  mysql_data: