spring.application.name=parking-management
server.port=${SERVER_PORT} || 3003

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true

# Configuration DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.sql.init.mode=always

# URL Simulator and webhook
garage.simulator.base-url=${GARAGE_SIMULATOR_BASE_URL}
app.webhook.url=${APP_WEBHOOK_URL}

# Timezone
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ